# Port that xsoverlay is listening on
port = 42069
# The hostname that xsoverlay is listening on
host = "localhost"
# The notification strategy - either "listener" or "polling"
notification_strategy = "polling"
# The rate at which the polling strategy refreshes notifications
polling_rate = 250
# The duration the notification shows up on screen
timeout = 2
# Your reading speed in words per minute (WPM). When dynamic_timeout is enabled, the timeout of each notification will be calculated based off of this.
reading_speed = 238
# When dynamic_timeout is enabled, notifications will never display for less than this many seconds.
min_timeout = 2
# When dynamic_timeout is enabled, notifications will never display for more than this many seconds.
max_timeout = 120