name: Package
on:
  workflow_dispatch:
  push:
    branches: [master]
env:
  CARGO_TERM_COLOR: always
jobs:
  package_and_publish:
    name: XSOverlay Notifier
    if: github.event_name == 'push'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Build
        env:
          SIGN_CERT: ${{ secrets.SIGN_CERT }}
          SIGN_CERT_PASSWORD: ${{ secrets.SIGN_CERT_PASSWORD }}
        shell: pwsh
        run: |
          .\.github\scripts\build.ps1
      - uses: actions/upload-artifact@v3
        with:
          name: XSOverlay Notifier
          path: ./out/XSOverlayNotifier.msix
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
          commit: "master"
          tag: "latest"
          artifacts: "./out/XSOverlayNotifier.msix,code_signing.crt,install.ps1"
